# Custom message definitions.
#
# rviz2 and "ros2 topic echo" can list a topic without its type, but cannot
# deserialise it. Types in apt come from EXTRA_APT; types built only on the
# robot are mirrored here as interface-only packages and compiled into the
# local image. A mirror generates identical type support because that depends
# on the package name and the field definitions, not on the rest of the package.

MSGS_DIR() { echo "$RRV_ROOT/msgs"; }

# Message packages currently on the ROS graph.
msgs_graph_packages() {
  "$RRV_ROOT/bin/rrv" run -p "$RRV_PROFILE" ros2 topic list -t 2>/dev/null \
    | sed -n 's/.*\[\([a-zA-Z0-9_]*\)\/msg\/.*/\1/p' | sort -u
}

# Packages already available in the local image.
msgs_local_packages() {
  docker run --rm "$P_IMAGE" bash -lc \
    'source /opt/ros/'"$R_DISTRO"'/setup.bash 2>/dev/null; \
     [ -f /opt/rrv_msgs/setup.bash ] && source /opt/rrv_msgs/setup.bash; \
     ros2 pkg list' 2>/dev/null | tr -d '\r' | sort -u
}

# Is there an apt package for it? Cheaper than building a mirror, and keeps the
# real definitions rather than a reconstruction.
msgs_apt_name() { echo "ros-$R_DISTRO-$(echo "$1" | tr '_' '-')"; }
# Check every candidate in ONE container: apt-get update dominates the cost, so
# doing it per package made this unusably slow.
# stdin: package names. stdout: those that exist in apt.
msgs_apt_filter() {
  local names="" p
  local -a want=()
  while read -r p; do [ -n "$p" ] && { want+=("$p"); names="$names $(msgs_apt_name "$p")"; }; done
  [ ${#want[@]} -eq 0 ] && return 0
  local found
  found=$(docker run --rm "$P_IMAGE" bash -c \
    "apt-get update -qq >/dev/null 2>&1
     for n in$names; do
       apt-cache policy \$n 2>/dev/null | grep -q 'Candidate: [0-9]' && echo \$n
     done" 2>/dev/null | tr -d '\r')
  for p in "${want[@]}"; do
    printf '%s\n' "$found" | grep -qx "$(msgs_apt_name "$p")" && echo "$p"
  done
  return 0
}

# Where the remote container keeps a package's interface files.
_remote_iface_dir() {
  local pkg="$1"
  rsh "docker exec $R_CONTAINER bash -lc '
    for d in \$(find / -type d -name \"$pkg\" -path \"*/share/*\" 2>/dev/null); do
      if [ -d \"\$d/msg\" ] || [ -d \"\$d/srv\" ] || [ -d \"\$d/action\" ]; then echo \"\$d\"; break; fi
    done'" 2>/dev/null | tr -d '\r' | head -1
}

# Other interface packages referenced by these definitions.
_scan_deps() {
  local dir="$1" self="$2"
  { grep -rhoE '^[[:space:]]*[a-z][a-z0-9_]*/[A-Z][A-Za-z0-9]*' "$dir" 2>/dev/null \
      | sed 's#[[:space:]]*##; s#/.*##'
    # builtin_interfaces is implied by any header/time field
    grep -rqE '^[[:space:]]*(std_msgs/Header|builtin_interfaces)' "$dir" 2>/dev/null && echo builtin_interfaces
  } | sort -u | grep -v "^$self$" | grep -vE '^(bool|byte|char|float32|float64|int8|uint8|int16|uint16|int32|uint32|int64|uint64|string|wstring)$'
}

_write_pkg_files() {
  local dir="$1" pkg="$2"
  local deps; deps=$(_scan_deps "$dir" "$pkg")

  { echo '<?xml version="1.0"?>'
    echo '<package format="3">'
    echo "  <name>$pkg</name>"
    echo '  <version>0.0.0</version>'
    echo '  <description>Interface-only mirror generated by rrv. Do not edit by hand.</description>'
    echo '  <maintainer email="none@example.invalid">rrv</maintainer>'
    echo '  <license>TODO</license>'
    echo '  <buildtool_depend>ament_cmake</buildtool_depend>'
    echo '  <buildtool_depend>rosidl_default_generators</buildtool_depend>'
    local d; for d in $deps; do echo "  <depend>$d</depend>"; done
    echo '  <exec_depend>rosidl_default_runtime</exec_depend>'
    echo '  <member_of_group>rosidl_interface_packages</member_of_group>'
    echo '  <export><build_type>ament_cmake</build_type></export>'
    echo '</package>'; } > "$dir/package.xml"

  local files=""
  local f
  for f in $(cd "$dir" && find msg srv action -type f \
               \( -name '*.msg' -o -name '*.srv' -o -name '*.action' \) 2>/dev/null | sort); do
    files="$files
  \"$f\""
  done

  { echo 'cmake_minimum_required(VERSION 3.8)'
    echo "project($pkg)"
    echo 'find_package(ament_cmake REQUIRED)'
    echo 'find_package(rosidl_default_generators REQUIRED)'
    local d; for d in $deps; do echo "find_package($d REQUIRED)"; done
    echo 'rosidl_generate_interfaces(${PROJECT_NAME}'
    printf '%s\n' "$files"
    [ -n "$deps" ] && echo "  DEPENDENCIES $(echo $deps)"
    echo ')'
    echo 'ament_package()'; } > "$dir/CMakeLists.txt"
}

cmd_msgs() {
  local action="${1:-status}"; [ $# -gt 0 ] && shift

  local graph local_pkgs missing
  step "Inspecting the ROS graph"
  graph="$(msgs_graph_packages)"
  [ -n "$graph" ] || die "no message types seen on the graph.
Is the remote actually publishing? Try: rrv run ros2 topic list"
  local_pkgs="$(msgs_local_packages)"
  missing="$(comm -23 <(printf '%s\n' "$graph") <(printf '%s\n' "$local_pkgs"))"

  if [ -z "$missing" ]; then
    ok "every message package on the graph is available locally"
    return 0
  fi

  step "Missing locally"
  local in_apt; in_apt="$(printf '%s\n' "$missing" | msgs_apt_filter)"
  local apt_list="" src_list="" p
  for p in $missing; do
    if printf '%s\n' "$in_apt" | grep -qx "$p"; then
      info "  $p  $C_DIM(apt: $(msgs_apt_name "$p"))$C_RST"
      apt_list="$apt_list $(msgs_apt_name "$p")"
    else
      info "  $p  $C_DIM(no apt package - mirror from the robot)$C_RST"
      src_list="$src_list $p"
    fi
  done

  if [ "$action" = status ]; then
    echo
    [ -n "$apt_list" ] && info "Add to config/$RRV_PROFILE.env:
  EXTRA_APT=\"$(echo $apt_list)\""
    [ -n "$src_list" ] && info "Mirror the rest with:  rrv msgs sync"
    return 0
  fi
  [ "$action" = sync ] || die "usage: rrv msgs [status|sync]"

  # Mirror the ones apt cannot provide.
  if [ -n "$src_list" ]; then
    mkdir -p "$(MSGS_DIR)"
    for p in $src_list; do
      step "Mirroring $p"
      local rdir; rdir="$(_remote_iface_dir "$p")"
      [ -n "$rdir" ] || { warn "  no interface files found for $p in $R_CONTAINER - skipping"; continue; }
      dim "  from $R_CONTAINER:$rdir"
      local out; out="$(MSGS_DIR)/$p"
      rm -rf "$out"; mkdir -p "$out"
      local sub
      for sub in msg srv action; do
        # -h dereferences symlinks: a workspace built with colcon
        # --symlink-install has these files pointing back into its source tree,
        # and archiving the links alone yields broken symlinks on this machine.
        rsh "docker exec $R_CONTAINER sh -c 'cd $rdir && tar chf - $sub 2>/dev/null'" \
          > "$out/.x.tar" 2>/dev/null || true
        if [ -s "$out/.x.tar" ]; then
          tar xf "$out/.x.tar" -C "$out" 2>/dev/null || true
        fi
        rm -f "$out/.x.tar"
      done
      # Drop generated artefacts that sit alongside the real definitions.
      # Every branch must succeed: a bare find over a missing directory returns
      # non-zero and would abort the whole run under `set -e`.
      find "$out" -name '*.idl' -delete 2>/dev/null || true
      # Service request/response halves are generated from the .srv; keeping them
      # would make rosidl declare the same types twice.
      if [ -d "$out/srv" ]; then
        find "$out/srv" \( -name '*_Request.msg' -o -name '*_Response.msg' \) \
          -delete 2>/dev/null || true
      fi
      local n; n=$(find "$out" -type f \( -name '*.msg' -o -name '*.srv' -o -name '*.action' \) | wc -l)
      [ "$n" -gt 0 ] || { warn "  copied nothing for $p - skipping"; rm -rf "$out"; continue; }
      _write_pkg_files "$out" "$p"
      ok "  $n interface files -> msgs/$p"
    done
  fi

  echo
  if [ -n "$apt_list" ]; then
    warn "Also add to config/$RRV_PROFILE.env, then rebuild:
     EXTRA_APT=\"$(echo $apt_list)\""
  fi
  info "Now run: rrv build"
}
